### PR TITLE
How about this - use a single file for the whole example

### PR DESCRIPTION
**Pull request by harendra-kumar**
That way the flow is quicker to understand. 

Also, we can add more example modules later, one module per scenario and rename this repo to something like `servant-examples`.

### CODE REVIEW

**Comment by soenkehahn** [comment]
I don't really have a strong opinion on this. @alpmestan, @mchaver, do you have objections or opinions?

Note though, that there are other `example-servant-...` repos already.

**Comment by harendra-kumar** [comment]
After looking at the cookbook examples page, on second thoughts my latter comment about adding more examples to this becomes irrelevant. Just adding individual repos to the examples page is also a good way to collect all examples at one place.

So this PR is just about putting everything together in a file, in sequence, for quicker understanding of the flow.

**Comment by andys8** [comment]
I'm not sure if we should throw the code in a single file. Someone who uses this as a start for a first project has to figure out how to structure and extract the code as the codebase starts to grow.

**Comment by harendra-kumar** [comment]
@andys8 I disagree with that argument. I think the primary purpose and focus of these examples should be to attract (and not repel) new folks to servant by giving them a good understanding of how things work in as little time as possible. Once they are in they will figure things out. If someone is working on a large project they better know how to structure it, that should not be the goal here.

**Comment by alpmestan** [comment]
I'm personally hoping for [the cookbook](https://haskell-servant.readthedocs.io/en/latest/cookbook/index.html) to become the go-to place to find examples like this, with recipes contributed by about anyone who offers reasonable code and explanations in a PR. The single-file restriction makes sense there but in this repo? Not sure, as you could indeed show how one can structure a servant app already, even for this simple example, and have the simpler single-file version in the cookbook. But that's just my personal opinion :)

**Comment by harendra-kumar** [comment]
ok, I will go with that and close this PR.

**Pull request closed without merging**
