### PR TITLE
Use stack lts-10.0

### PR DESCRIPTION
**Pull request by harendra-kumar**

### CODE REVIEW

**Comment by alpmestan** [comment]
LGTM.

**Comment by andys8** [comment]
I appreciate the changes :)

**Comment by soenkehahn** [comment]
No, no objections at all.

**Comment by soenkehahn** [comment]
@harendra-kumar: I invited you as a collaborator to this repo. Feel free to merge this PR.

**Comment by harendra-kumar** [comment]
Thanks all! I merged the PR.

**Comment by alpmestan** [comment]
While there's a bit of activity... Please also note that servant now has a cookbook (at https://haskell-servant.readthedocs.io/en/latest/cookbook/index.html), where each recipe is an individual cabal project with an .lhs file that contains the explanations and the code, which allows us to check the code in CI. It might be nice to have a recipe for using persistent and servant together, if anyone feels like putting it together. All the existing recipes live at https://github.com/haskell-servant/servant/tree/master/doc/cookbook.

**Comment by harendra-kumar** [comment]
BTW, this repo is already linked from the examples page of cookbook: https://haskell-servant.readthedocs.io/en/stable/examples.html .

**Comment by alpmestan** [comment]
Thats not the cookbook, just some page in the docs. The cookbook is its own section there and only on master.

**Pull request merged**
